### ISSUE TITLE
Curl::Err::RecvError: Failure when receiving data from the peer

### ISSUE THREAD

**Issue by deanobarnett** [sportngin/active_zuora#57]
We are seeing `Curl::Err::RecvError: Failure when receiving data from the peer` when making requests to Zuora through ActiveZuora. Using cURL on the same endpoints seem to be fine.

Has anyone come across this?

**Comment by baxang** [comment]
Hi @deanobarnett I had the same issue after I added `curb` gem to my app. AFAIK, it is because ActiveZuora uses `savon` and `savon` picks up `curb` as its HTTP backend (to be precise, it is done by HTTPI gem that is used by `savon`).

ActiveZuora doesn't allow us to configure what HTTP backend should be used, but I could workaround the issue by adding a line of code to `config/initializers/active_zuora.rb`.

````ruby
HTTPI.adapter = :net_http
````

**Comment by anfleene** [comment]
Wow! @baxang Thanks for helping :+1:  You should add these details to the README. Unless you have any good ideas about how we can support it better.

**Comment by JoshReedSchramm** [comment]
@baxang Thanks! We're also using savon (although not through active_zuora) and ran into the same issue.
